language: node_js
node_js:
  - '6'
  - '8'

before_script:
  - npm run lint
  
install:
  - npm install
  - npm install -g istanbul
  - npm install -g codecov
  
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  
test:
  npm test

notifications:
  email:
    on_success: never
